### ISSUE TITLE
Presentation from Tuesday night?

### ISSUE THREAD

**Issue by kdenny** [notthatbreezy/phl-play#1]
Hey Chris,

I really enjoyed the presentation you gave on the creation of this app at the GeoPhilly meetup Tuesday - is there any way you could upload it to this repo? I am sure a lot of people would find it as a very useful reference!

Thanks,
Kevin

**Comment by notthatbreezy** [comment]
That's a great idea, I just added it to the repository.

**Comment by kdenny** [comment]
Awesome, thanks Chris!
